#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only

set -eu

project_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
headers_dir=${PLF110_HEADERS_DIR:-}
kernel_source=${PLF110_KERNEL_SOURCE:-}
display_root=${PLF110_DISPLAY_ROOT:-}
clang=${PLF110_CLANG:-}
linker=${PLF110_LD_LLD:-}
readelf=${PLF110_READELF:-llvm-readelf}
nm=${PLF110_NM:-llvm-nm}
objdump=${PLF110_OBJDUMP:-llvm-objdump}
module_name=${PLF110_MODULE_NAME:-PLF110_Display_OC}
output_dir=${PLF110_OUTPUT_DIR:-$project_root/out}
source_file=$project_root/src/PLF110_144_Mode.c

fail() {
	echo "error: $*" >&2
	exit 1
}

[ -n "$headers_dir" ] || fail "PLF110_HEADERS_DIR is required"
[ -n "$kernel_source" ] || fail "PLF110_KERNEL_SOURCE is required"
[ -n "$display_root" ] || fail "PLF110_DISPLAY_ROOT is required"
[ -n "$clang" ] || fail "PLF110_CLANG is required"
[ -n "$linker" ] || fail "PLF110_LD_LLD is required"
[ -f "$source_file" ] || fail "missing source: $source_file"
[ -f "$headers_dir/include/linux/compiler-version.h" ] || \
	fail "incomplete generated kernel headers: $headers_dir"
[ -f "$headers_dir/include/linux/kconfig.h" ] || \
	fail "incomplete generated kernel headers: $headers_dir"
[ -f "$kernel_source/scripts/module.lds.S" ] || \
	fail "missing module linker script below: $kernel_source"
[ -f "$display_root/drivers/gpu/drm/mediatek/mediatek_v2/mtk_dsi.h" ] || \
	fail "missing MTK DSI ABI headers below: $display_root"
[ -x "$clang" ] || fail "clang is not executable: $clang"
[ -x "$linker" ] || fail "ld.lld is not executable: $linker"
command -v "$readelf" >/dev/null 2>&1 || fail "missing tool: $readelf"
command -v "$nm" >/dev/null 2>&1 || fail "missing tool: $nm"
command -v "$objdump" >/dev/null 2>&1 || fail "missing tool: $objdump"

compiler_version=$("$clang" --version | sed -n '1p')
case "$compiler_version" in
	*"clang version 21.1.8"*) ;;
	*) fail "unexpected compiler: $compiler_version (validated build uses Clang 21.1.8)" ;;
esac

display_driver=$display_root/drivers/gpu/drm/mediatek/mediatek_v2
display_include=$display_root/include
interconnect_dir=$display_root/drivers/misc/mediatek/mtk-interconnect
cmdq_dir=$display_root/drivers/misc/mediatek/cmdq/mailbox
mtk_platform_include=$display_root/drivers/misc/mediatek/include/mt-plat
mkdir -p "$output_dir"

"$clang" \
	--target=aarch64-linux-gnu \
	-E -P -x assembler-with-cpp \
	-D__KERNEL__ -D__ASSEMBLY__ \
	-include "$headers_dir/include/linux/compiler-version.h" \
	-include "$headers_dir/include/linux/kconfig.h" \
	-I"$headers_dir/arch/arm64/include" \
	-I"$headers_dir/arch/arm64/include/generated" \
	-I"$headers_dir/include" \
	-I"$headers_dir/arch/arm64/include/uapi" \
	-I"$headers_dir/arch/arm64/include/generated/uapi" \
	-I"$headers_dir/include/uapi" \
	-I"$headers_dir/include/generated/uapi" \
	"$kernel_source/scripts/module.lds.S" \
	-o "$output_dir/module.lds"

"$clang" \
	--target=aarch64-linux-gnu \
	-std=gnu11 -O2 \
	-D__KERNEL__ -DMODULE \
	-DCONFIG_MTK_CMDQ_MBOX_EXT=1 \
	-"DKBUILD_MODNAME=\"$module_name\"" \
	-"DKBUILD_BASENAME=\"$module_name\"" \
	-include "$headers_dir/include/linux/compiler-version.h" \
	-include "$headers_dir/include/linux/kconfig.h" \
	-I"$headers_dir/arch/arm64/include" \
	-I"$headers_dir/arch/arm64/include/generated" \
	-I"$headers_dir/include" \
	-I"$headers_dir/arch/arm64/include/uapi" \
	-I"$headers_dir/arch/arm64/include/generated/uapi" \
	-I"$headers_dir/include/uapi" \
	-I"$headers_dir/include/generated/uapi" \
	-I"$display_driver" \
	-I"$interconnect_dir" \
	-I"$display_include" \
	-I"$cmdq_dir" \
	-I"$mtk_platform_include" \
	-Wall -Wextra -Werror \
	-Wno-unused-parameter \
	-Wno-pointer-sign \
	-Wno-sign-compare \
	-Wno-gnu-variable-sized-type-not-at-end \
	-fno-pic -fno-PIE -fno-common -fno-builtin \
	-fno-stack-protector -fno-asynchronous-unwind-tables \
	-fno-unwind-tables -fno-delete-null-pointer-checks \
	-fno-strict-overflow -fno-optimize-sibling-calls \
	-fno-omit-frame-pointer -ffixed-x18 \
	-fsanitize=kcfi \
	-fsanitize-cfi-icall-experimental-normalize-integers \
	-mbranch-protection=pac-ret -mgeneral-regs-only -mstrict-align \
	-mno-outline-atomics -mcmodel=large \
	-c "$source_file" \
	-o "$output_dir/$module_name.o"

"$linker" \
	-r -m aarch64elf -z noexecstack --build-id=sha1 \
	-T "$output_dir/module.lds" \
	-o "$output_dir/PLF110_144_Mode.ko" \
	"$output_dir/$module_name.o"

# The target 6.1.157 kernel was built with the module trampoline type IDs below.
# Clang emits different hashes for the alias generated by module_init/module_exit;
# leave the function bodies untouched and normalize only those four-byte CFI
# words before the artifact can be loaded. Section offsets are resolved from the
# linked ELF, so adding code does not invalidate this step.
patch_cfi_word() {
	section=$1
	bytes=$2
	offset=$("$readelf" -SW "$output_dir/PLF110_144_Mode.ko" |
		awk -v wanted="$section" '$2 == wanted { print "0x" $5; exit }')
	[ -n "$offset" ] || fail "missing section: $section"
	printf '%b' "$bytes" | dd of="$output_dir/PLF110_144_Mode.ko" \
		bs=1 seek=$((offset)) conv=notrunc status=none ||
		fail "failed to patch $section CFI word"
}

patch_cfi_word .init.text '\246\305\261\066'
patch_cfi_word .exit.text '\014\147\100\245'

# Normalize vendor KCFI IDs for module-parameter and kretprobe callbacks.
patch_symbol_cfi() {
	symbol=$1
	bytes=$2
	text_offset=$($readelf -SW "$output_dir/PLF110_144_Mode.ko" |
		awk '$2 == ".text" { print "0x" $5; exit }
		     $3 == ".text" { print "0x" $6; exit }')
	address=$($nm -n "$output_dir/PLF110_144_Mode.ko" |
		awk -v wanted="$symbol" '$3 == wanted { print "0x" $1; exit }')
	[ -n "$text_offset" ] || fail "missing .text section"
	[ -n "$address" ] || fail "missing callback symbol: $symbol"
	seek=$((text_offset + address - 4))
	printf '%b' "$bytes" | dd of="$output_dir/PLF110_144_Mode.ko" \
		bs=1 seek=$seek conv=notrunc status=none ||
		fail "failed to patch callback CFI word: $symbol"
}

# Vendor kernel KCFI IDs for struct kernel_param_ops callbacks.
for symbol in enable_set refresh_set; do
	patch_symbol_cfi "$symbol" '\234\177\372\143'
done
for symbol in enable_get status_get modes_get; do
	patch_symbol_cfi "$symbol" '\374\075\114\306'
done
# DRM/panel replacement callbacks use the type IDs carried by the known-good
# 144 Hz module for this exact kernel build.
patch_symbol_cfi plf110_panel_get_modes '\006\135\313\114'
patch_symbol_cfi plf110_connector_fill_modes '\073\246\301\237'
patch_symbol_cfi plf110_mode_switch_update_for_vdo '\073\246\301\237'
patch_symbol_cfi plf110_ext_param_set '\237\031\363\074'
patch_symbol_cfi plf110_ext_param_get '\360\103\352\367'
patch_symbol_cfi panel_pre_handler '\331\135\276\246'
patch_symbol_cfi porch_pre_handler '\331\135\276\246'
# 0x8078be15: struct kretprobe entry/return callbacks.
for symbol in plf110_enum_entry plf110_enum_ret ofp_entry ofp_ret vref_ret; do
	patch_symbol_cfi "$symbol" '\025\276\170\200'
done

# Normalize the DSI io_cmd indirect-call type to the value used by the
# known-good 144 Hz module. Clang derives 0xac8d9276 for the inline helper,
# but the target vendor kernel rejects that ID at the first mode switch.
patch_callsite_cfi() {
	old_low=$1
	old_high=$2
	new_low_bytes=$3
	new_high_bytes=$4
	text_offset=$($readelf -SW "$output_dir/PLF110_144_Mode.ko" |
		awk '$2 == ".text" { print "0x" $5; exit }
		     $3 == ".text" { print "0x" $6; exit }')
	[ -n "$text_offset" ] || fail "missing .text section"
	addresses_file=$output_dir/.callsite-cfi-addresses
	: > "$addresses_file"
	"$objdump" -d "$output_dir/PLF110_144_Mode.ko" |
		awk -v wanted="$old_low" '$2 == wanted {
			sub(/:$/, "", $1); print $1
		}' > "$addresses_file"
	count=$(wc -l < "$addresses_file" | tr -d ' ')
	[ "$count" -gt 0 ] || fail "no call-site CFI words found for $old_low"
	while IFS= read -r address; do
		seek=$((text_offset + 0x$address))
		printf '%b' "$new_low_bytes" | dd of="$output_dir/PLF110_144_Mode.ko" \
			bs=1 seek=$seek conv=notrunc status=none ||
			fail "failed to patch call-site CFI low word at $address"
		printf '%b' "$new_high_bytes" | dd of="$output_dir/PLF110_144_Mode.ko" \
			bs=1 seek=$((seek + 4)) conv=notrunc status=none ||
			fail "failed to patch call-site CFI high word at $address"
	done < "$addresses_file"
	rm -f "$addresses_file"
	echo "patched call-site CFI: $count ($old_low/$old_high)"
}

patch_callsite_cfi 72924ed1 72b591b1 '\061\166\212\162' '\121\104\277\162'
# The same compiler/ABI difference affects calls into the original vendor
# panel callbacks. Normalize each call-site family to the IDs in the working
# module; these are call-site immediates, not function-body changes.
patch_callsite_cfi 728ff5d1 72a94911 '\361\063\203\162' '\161\236\247\162'
patch_callsite_cfi 7295dc11 72a98d31 '\021\176\210\162' '\121\375\276\162'
patch_callsite_cfi 729d0291 72a010f1 '\321\240\213\162' '\161\231\251\162'
patch_callsite_cfi 72988dd1 72a28fb1 '\161\307\224\162' '\061\370\263\162'

echo "compiler: $compiler_version"
echo "source:   $source_file"
echo "output:   $output_dir/PLF110_144_Mode.ko"
